name: Run indexMaker and Deploy Pages

on:
  push:
    branches:
      - main
      - master
      - '**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Adjust Node.js version as needed

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with the Python version you need

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have any requirements

      - name: Run indexMaker.py
        run: |
          python indexMaker.py

      # Commit changes made by Python script
      - name: Commit changes
        run: |
          git config --local user.name "gitrykt[bot]"
          git config --local user.email "gitrykt[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update index.html with new paths"
          git push

      # Deploy pages (example using GitHub Pages)
      - name: Deploy Pages
        if: success()  # Only deploy if previous steps were successful
        run: |
          git checkout gh-pages  # Switch to your branch where pages are deployed
          git pull origin gh-pages  # Ensure you have latest changes
          # Run any build commands needed for your pages (e.g., npm run build)
          npm install  # Example, install dependencies if needed
          npm run build  # Example, build your pages

          # Commit and push changes to deploy
          git add .
          git commit -m "Deploy updated pages"
          git push origin gh-pages

      # Restore to the original branch (main/master)
      - name: Restore to main/master branch
        run: git checkout ${{ github.ref }}

